# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.cache/wt} [current_project]
set_property parent.project_path {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/new/color_byte.sv}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/new/color_scrambler.sv}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/new/driver_vga.sv}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/new/gray_scale.sv}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 8/sesion_8_casi_final.xpr/sesion_8_ahora_si/sesion_8_ahora_si.srcs/sources_1/new/le_display.sv}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/new/TOP_9.sv}
}
read_verilog -library xil_defaultlib {
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 7/reference/data_sync.v}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 7/uart_basic.v}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 7/uart_baud_tick_gen.v}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 7/uart_rx.v}
  {C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/imports/Lab. Digitales/sesion 7/uart_tx.v}
}
read_ip -quiet {{C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/fgarrido/Desktop/sesion 9_SEN/sesion 9_SEN/sesion 9/sesion 9.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc}}]


synth_design -top TOP_9 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_9.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_9_utilization_synth.rpt -pb TOP_9_utilization_synth.pb"
